version: "3.9"
services:
  test:
    image: node:14
    volumes:
      - .:/opt/app
    links:
      - mongo:mongo
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/?replicaSet=0
    working_dir: /opt/app
    command: 'bash -c "npm install && npm run test"'

  mongo:
    image: mongo:4.4
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
